#!/bin/sh

# Start sxhkd if not already running
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width 2
bspc config focused_border_color "#cba6f7"
bspc config active_border_color "#181825"
bspc config presel_feedback_color "#fab387"
bspc config normal_border_color "#181825"

# Configure BSPWM monitors and desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Settings
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config single_monocle true
bspc config pointer_modifier shift

# Autostart applications
picom --config "$HOME/.config/picom/picom.conf" &
nitrogen --set-zoom-fill "$PRIME/pics/wallpaper/arch.png" &
dunst &
xmodmap "$HOME/.config/xmodmap/xmodmap" &
kitty &

# Stop cursor from being an "X" when not over a window
xsetroot -cursor_name left_ptr &
